language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
env:
- PLONE_VERSION=4.3 EXTRAS=buildout:package-extras=[test,archetypes]
- PLONE_VERSION=4.3 EXTRAS=buildout:package-extras=[test,dexterity]
matrix:
  fast_finish: true
install:
- sed -ie "s#test-4.3.x.cfg#test-$PLONE_VERSION.x.cfg#" buildout.cfg
- python bootstrap.py
- bin/buildout $EXTRAS annotate
- bin/buildout $EXTRAS
script:
- bin/test
after_success:
- bin/createcoverage
- pip install coveralls
- coveralls
notifications:
  irc: irc.freenode.org#plone-testing
